cargo-features = ["panic-immediate-abort"]

[package]
name = "bootlogo"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = "z"
codegen-units = 1
panic = "immediate-abort"
lto = true
strip = true
